### ISSUE TITLE
【调研】添加悬浮显示查询结果的功能

### ISSUE THREAD

**Issue by mrchar** [program-in-chinese/vscode_english_chinese_dictionary#33]
最近喜欢上了在禅模式下进行工作，但是遇到要查询的单词每次都要推出禅模式才能看到释义，这真的很麻烦，请问有什么办法解决这个问题吗？

**Comment by mrchar** [comment]
不好意思，我检查了以下vscode的设置，禅模式可以调出状态栏，问题解决了。

**Comment by nobodxbodon** [comment]
你好，发觉最近几天似乎安装量上去不少，敢问是从哪里得知此插件的？

**Comment by mrchar** [comment]
我原来用的vscode-ecdict这个插件，它可以直接查询指针所指的单词。但是在最新的vscode的他已经不能工作了，我看到作者已经将项目归档了，所以就在网上找类似的插件，可是找到的都是选中文字之后需要右键翻译或者使用快捷键的插件。我是在知乎上看到您写的文章才找到这个插件的。请问您是否有兴趣添加悬浮显示查询结果的功能，这样我就不需要在点击状态栏上的结果才能查看详情了。

**Comment by nobodxbodon** [comment]
多谢告知。最近空闲很少，有机会看看 [vscode-ecdict](https://github.com/voldikss/vscode-ecdict/) 的实现，如能方便借鉴的话，争取改进一下。暂打开 issue，作下备忘。。

**Comment by nobodxbodon** [comment]
@mrchar 刚试了在1.44.2下 ecdict 插件好像还能用啊：
![Screen Shot 2020-04-30 at 1 58 14 AM](https://user-images.githubusercontent.com/392497/80692353-4bc9f980-8a86-11ea-9042-72c6cf51a819.png)

**Comment by mrchar** [comment]
我也不确定发生了什么问题，在我的电脑上ecdict确实没有运行，我用的也是1.44.2。

**Comment by nobodxbodon** [comment]
亏得能人相助，1.1.0 已有此功能。
