### ISSUE TITLE
希望为插件添加一个Icon

### ISSUE THREAD

**Issue by refcell** [program-in-chinese/vscode_english_chinese_dictionary#37]
![image](https://user-images.githubusercontent.com/14192199/93035047-88317700-f66e-11ea-961e-81ea25b4d580.png)
如图，打开插件列表就看到排首位的本插件，光秃秃的看着很不和谐，希望作者能为其设置一个Icon

**Comment by nobodxbodon** [comment]
欢迎 pr。

**Comment by nobodxbodon** [comment]
多谢美化。
