### ISSUE TITLE
翻译结果显示

### ISSUE THREAD

**Issue by lupengge** [program-in-chinese/vscode_english_chinese_dictionary#44]
希望能添加一个设置，将翻译结果显示成悬浮的或者状态栏，个人感觉悬浮的更方便

**Comment by nobodxbodon** [comment]
之前有类似请求，如有补充不妨在 https://github.com/program-in-chinese/vscode_english_chinese_dictionary/issues/33 继续。

**Comment by nobodxbodon** [comment]
1.1.0 已添加此功能，请见首页说明选项设置。
