### ISSUE TITLE
希望支持ssh模式

### ISSUE THREAD

**Issue by vipfrog** [program-in-chinese/vscode_english_chinese_dictionary#67]
我在windows的vscode里，使用remote ssh连接linux服务器打开远程项目，此时观察插件状态，本地的“翻译(英汉词典)”插件不开启，SSH上的“翻译(英汉词典)”插件开启。问题是实际上打开项目后，插件并没有在vscode正常启动。无论是鼠标悬停，还是下方状态栏翻译，或者是批量翻译，都无效。
请大大看一看，谢谢。

**Comment by nobodxbodon** [comment]
手边没有ssh环境，恕难重现。

**Comment by vipfrog** [comment]
稍微学了下调试插件，才发现是我自己的问题。因为插件里有些文件是中文的，我zip压缩传到linux上后用unzip解压，遇到字符集没匹配的情况所以解压后插件里的文件名汉字都被改成UTF8编码值了，造成插件加载失败，未找到相关文件。文件名修正后插件可以正常在ssh模式下使用，此问题关闭。也感谢作者的答复，插件确实好用，点赞支持！

**Comment by nobodxbodon** [comment]
感谢调试及分享解决方案！
